#!/bin/sh

if [ -n "${DO_LEGACY_VNC}" ]; then
    # Based on:
    # https://bytexd.com/how-to-install-configure-vnc-server-on-ubuntu/

    # Start up the standard system desktop
    unset SESSION_MANAGER
    unset DBUS_SESSION_BUS_ADDRESS

    /usr/bin/startxfce4
    #/usr/bin/mate-session
    #/usr/bin/cinnamon-session

    [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
    [ -r "$HOME"/.Xresources ] && xrdb "$HOME"/.Xresources
    x-window-manager &
else
    # This is needed for copy+paste to work in some environments
    vncconfig -nowin &

    # The below is the default generated xstartup file when vncserver
    # (tigervnc-server) was run on RHEL7.9 (with some shellcheck fix-ups
    # applied).
    unset SESSION_MANAGER
    unset DBUS_SESSION_BUS_ADDRESS

    /etc/X11/xinit/xinitrc
    # Assume either Gnome or KDE will be started by default when installed We
    # want to kill the session automatically in this case when user logs out. In
    # case you modify /etc/X11/xinit/Xclients or ~/.Xclients yourself to achieve
    # a different result, then you should be responsible to modify below code to
    # avoid that your session will be automatically killed
    if [ -e /usr/bin/gnome-session ] || [ -e /usr/bin/startkde ]; then
	vncserver -kill "$DISPLAY"
    fi
fi
