#!/bin/sh

# Copied from:
# https://bytexd.com/how-to-install-configure-vnc-server-on-ubuntu/

# Start up the standard system desktop
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

/usr/bin/startxfce4
#/usr/bin/mate-session
#/usr/bin/cinnamon-session

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
x-window-manager &
